### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by iagocq** [vSLG/KeaKernel#1]
Hello! Long time no see :wave:

Currently the project has no clear licensing information, but I believe licensing the project is important for various reasons (including compatibility with KeaOS/2's code).

What do you think about this?

**Comment by vSLG** [comment]
Sure, you are correct. I was expecting you to ask regarding this, I would license KeaOS/3 the same way as KeaOS/2. Any thoughts about that?

**Comment by iagocq** [comment]
Seems fine to me :+1:

**Comment by vSLG** [comment]
Fixed by [bb35ee01](https://github.com/vSLG/KeaKernel/commit/bb35ee01a5143c0f6bb6059a4428ecbe9f52812e).
